<?xml version="1.0"?>
<!-- Scara Manipulator -->
<robot name="scararobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="mass" value="1" />
  <xacro:property name="base_height" value="1.2" />
  <xacro:property name="base_width" value="0.3" />
  <xacro:property name="wrist_point" value="0.01" />
  <xacro:property name="first_joint_angle" value="2.6" />
  <xacro:property name="second_joint_angle" value="2.6" />
  
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find scara_robot)/xacro/scararobot.gazebo" />  

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0"/> 
  </joint>

  <link name="world"/>


  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_height}" radius="${base_width/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${base_height/2}"/>
      <material name="White">
        <color rgba="255.0 255.0 255.0 1.0"/>
      </material>  
    </visual>

    <collision>
      <geometry>
        <cylinder length="${base_height}" radius="${base_width/2}" />
      </geometry>
    </collision>
    
    <inertial>
      <mass value="${mass}"/>
      <inertia
      	  ixx="${mass / 12.0 * (base_width*base_width + base_height*base_height)}" ixy="0.0" ixz="0.0"
	        iyy="${mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
	        izz="${mass / 12.0 * (base_width*base_width + base_width*base_width)}"/>
    </inertial>
  </link>


  <link name="first_link">
    <visual>
      <geometry>
        <box size="${base_height * 0.75} ${base_width/2} ${base_width}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${base_height * 0.375 + base_width / 2} 0 0"/>
      <material name="White" />
    </visual>

    <collision>
      <geometry>
        <box size="${base_height * 0.75} ${base_width/2} ${base_width}"/>
      </geometry>
    </collision>
    
    <inertial>
      <mass value="${mass}"/>
      <inertia
	      ixx="${mass / 12.0 * ((base_width/2)*(base_width/2) + base_width*base_width)}" ixy="0.0" ixz="0.0"
	      iyy="${mass / 12.0 * ((base_height * 0.75)*(base_height * 0.75) + base_width*base_width)}" iyz="0.0"
	      izz="${mass / 12.0 * ((base_height * 0.75)*(base_height * 0.75) + (base_width/2)*(base_width/2))}"/>

    </inertial>
  </link>

  <link name="first_joint">
    <visual>
      <geometry>
        <cylinder length="${base_height * 0.25}" radius="${base_width/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material> 
    </visual>

    <collision>
      <geometry>
        <cylinder length="${base_height * 0.25}" radius="${base_width/2}"/>
      </geometry>
    </collision>
    
    <inertial>
      <mass value="${mass}"/>
      <inertia
      	  ixx="${mass / 12.0 * (base_width*base_width + (base_height * 0.25)*(base_height * 0.25))}" ixy="0.0" ixz="0.0"
	        iyy="${mass / 12.0 * ((base_height * 0.25)*(base_height * 0.25) + base_width*base_width)}" iyz="0.0"
	        izz="${mass / 12.0 * (base_width*base_width + base_width*base_width)}"/>
    </inertial>
  </link>


  <link name="second_link">
    <visual>
      <geometry>
        <box size="${base_height * 0.75} ${base_width/2} ${base_width}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${base_height * 0.375 + base_width/2} 0 0"/>
      <material name="White" />
    </visual>

    <collision>
      <geometry>
        <box size="${base_height * 0.75} ${base_width/2} ${base_width}"/>
      </geometry>
    </collision>
    
    <inertial>
      <mass value="${mass}"/>
      <inertia
	      ixx="${mass / 12.0 * ((base_width/2)*(base_width/2) + base_width*base_width)}" ixy="0.0" ixz="0.0"
	      iyy="${mass / 12.0 * ((base_height * 0.75)*(base_height * 0.75) + base_width*base_width)}" iyz="0.0"
	      izz="${mass / 12.0 * ((base_height * 0.75)*(base_height * 0.75) + (base_width/2)*(base_width/2))}"/>

    </inertial>
  </link>



  <link name="third_link">
    <visual>
      <geometry>
        <cylinder length="${base_height * 0.5}" radius="${base_width/6}" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${-base_height * 0.125}"/>
      <material name="White"/>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${base_height * 0.5}" radius="${base_width/6}"/>
      </geometry>
    </collision>
    
    <inertial>
      <mass value="${mass}"/>
      <inertia
      	  ixx="${mass / 12.0 * ((base_width/3)*(base_width/3) + (base_height * 0.5)*(base_height * 0.5))}" ixy="0.0" ixz="0.0"
	        iyy="${mass / 12.0 * ((base_height * 0.5)*(base_height * 0.5) + (base_width/3)*(base_width/3))}" iyz="0.0"
	        izz="${mass / 12.0 * ((base_width/3)*(base_width/3) + (base_width/3)*(base_width/3))}"/>
    </inertial>
  </link>


  <link name="wrist_link">
    <visual>
      <geometry>
        <box size="${wrist_point} ${wrist_point*5} ${wrist_point*10}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${-wrist_point*5}"/>
      <material name="Red">
        <color rgba="255.0 0.0 0.0 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${wrist_point} ${wrist_point*5} ${wrist_point*10}"/>
      </geometry>
    </collision>
    
    <inertial>
      <mass value="${mass}"/>
      <inertia
	      ixx="${mass / 12.0 * ((wrist_point*5)*(wrist_point*5) + (wrist_point*10)*(wrist_point*10))}" ixy="0.0" ixz="0.0"
	      iyy="${mass / 12.0 * (wrist_point*wrist_point + (wrist_point*10)*(wrist_point*10))}" iyz="0.0"
	      izz="${mass / 12.0 * (wrist_point*wrist_point + (wrist_point*5)*(wrist_point*5))}"/>
    </inertial>
  </link>







  <joint name="base_to_first_link" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-first_joint_angle}" upper="${first_joint_angle}" velocity="0.5"/>
    <parent link="base_link"/>
      <child link="first_link"/>
    <origin rpy="0 0 0" xyz="0 0 ${base_height * 0.625}"/>
  </joint>

  <joint name="first_link_to_first_joint" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-second_joint_angle}" upper="${second_joint_angle}" velocity="0.5"/>
    <parent link="first_link"/>
      <child link="first_joint"/>
    <origin rpy="0 0 0" xyz="${base_height * 0.75 + base_width } 0 0"/>
  </joint>


  <joint name="first_joint_to_second_link" type="fixed">
    <parent link="first_joint"/>
      <child link="second_link"/>
    <origin xyz="0 0 0"/>
  </joint>

  <joint name="second_link_to_second_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="second_link"/>
      <child link="third_link"/>
    <origin rpy="0 0 0" xyz="${base_height * 0.75 + base_width } 0 0"/>
  </joint>


  <joint name="second_joint_to_third_joint" type="prismatic">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-base_height * 0.25}" upper="0" velocity="0.5"/>
    <parent link="third_link"/>
      <child link="wrist_link"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>




  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_first_link">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="base_to_first_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="first_link_to_first_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="first_link_to_first_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="second_link_to_second_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="second_link_to_second_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="second_joint_to_third_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="second_joint_to_third_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  

</robot>
