
scararobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  base_to_first_link_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_first_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  first_link_to_first_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: first_link_to_first_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  second_link_to_second_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: second_link_to_second_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  second_joint_to_third_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: second_joint_to_third_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
