scara:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  # Position Controllers ---------------------------------------
  base_to_first_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_first_joint
    pid: {p: 500.0, i: 2.0, d: 10.0}
  first_to_second_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: first_to_second_joint
    pid: {p: 500.0, i: 2.0, d: 10.0}
  second_to_third_joint_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: second_to_third_joint
    pid: {p: 500.0, i: 2.0, d: 10.0}

